name: Parse News
on:
  schedule:
    - cron: '0 6 * * *'  # Щодня о 06:00 UTC (09:00 EEST)
  workflow_dispatch:
permissions:
  contents: write
concurrency:
  group: parse-news
  cancel-in-progress: false
jobs:
  parse-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run parser
        run: |
          python parse_news.py
          echo "Перевірка вмісту news.json після парсингу:"
          if [ -f news.json ]; then
            cat news.json
          else
            echo "Файл news.json не створено, створюємо порожній"
            echo "[]" > news.json
          fi
      - name: Commit and push to main
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add news.json
          echo "Вміст news.json перед комітом:"
          cat news.json
          git commit -m 'Update news.json' || echo "No changes to commit"
          git push
      - name: Prepare files for deploy
        run: |
          mkdir -p deploy
          mv news.json deploy/news.json || echo "news.json не знайдено, створюємо порожній"
          [ -f deploy/news.json ] || echo "[]" > deploy/news.json
          touch deploy/.nojekyll
          echo "Вміст папки deploy перед деплоєм:"
          ls -la deploy/
          echo "Вміст deploy/news.json:"
          cat deploy/news.json
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          publish_branch: gh-pages
          keep_files: true
