name: Parse News
on:
  schedule:
    - cron: '0 6 * * *'  # Щодня о 06:00 UTC (09:00 EEST)
  workflow_dispatch:  # Дозволяє запуск вручну
permissions:
  contents: write  # Права на коміт і пуш
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  parse-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Повна історія для git pull
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      - name: Run parser
        run: python parse_news.py
      - name: Ensure docs directory
        run: |
          if [ ! -d "docs" ]; then
            echo "Створено папку docs"
            mkdir -p docs
          else
            echo "Папка docs уже існує"
          fi
          touch docs/.nojekyll
          echo "Створено або оновлено .nojekyll"
      - name: Check docs directory
        run: |
          echo "Перевірка вмісту docs/:"
          ls -la docs/
          echo "Вміст news.json:"
          cat docs/news.json
      - name: Commit and push to main
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          echo "Стан репозиторію перед комітом:"
          git status
          git add docs/
          git commit -m 'Update news.json and .nojekyll' || echo "No changes to commit"
          echo "Коміт успішно створено в гілці main"
          git fetch origin main
          git pull origin main --rebase
          git push origin main
          echo "Коміт успішно надіслано в гілку main"
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
        run: |
          echo "Розгорнуто docs/ у gh-pages"
