name: Parse News
on:
  schedule:
    - cron: '0 6 * * *'  # Щодня о 06:00 UTC (09:00 EEST)
  workflow_dispatch:  # Дозволяє запуск вручну
permissions:
  contents: write  # Для коміту в main і пушу в gh-pages
concurrency:
  group: parse-news
  cancel-in-progress: false
jobs:
  parse-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run parser
        run: |
          python parse_news.py
          echo "Перевірка вмісту docs/news.json після парсингу:"
          cat docs/news.json || echo "Файл docs/news.json не створено"
      - name: Commit and push to main
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add docs/news.json
          echo "Вміст news.json перед комітом:"
          cat docs/news.json
          git commit -m 'Update news.json' || echo "No changes to commit"
          git push
      - name: Prepare docs directory
        run: |
          mkdir -p docs
          mv docs/news.json docs/news.json || echo "news.json не знайдено, створюємо порожній"
          [ -f docs/news.json ] || echo "[]" > docs/news.json
          touch docs/.nojekyll
          echo "Вміст папки docs перед деплоєм:"
          ls -la docs/
          echo "Вміст docs/news.json:"
          cat docs/news.json
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          keep_files: true  # Зберігає існуючі файли в gh-pages
